### ISSUE TITLE
0.20.5: Metal shader compilation fails on M5 Max (MTLGPUFamilyMetal4) — MPPTensorOpsMatMul2d type mismatch

### ISSUE THREAD

**Issue by dextersecret** [ollama/ollama#15487]
the GPU family: MTLGPUFamilyApple10 (1010) block, the MPPTensorOpsMatMul2dImpl.h:3266:5: error: static_assert failed block, and the Ollama version.
NOTE: it works on 0.18.3 on the same hardware

**Comment by thejohnnybot** [comment]
same

**Comment by edmava8** [comment]
Same

**Comment by Winddfall** [comment]
same

**Comment by illimit3** [comment]
same

**Comment by alanhere** [comment]
**Confirming same issue on M5  MacBook Air**
I can reproduce this on a standard M5 MacBook Air (24 GB unified memory) running Ollama 0.20.6 attempting to load gemma4:e4b.

**Environment:**
Hardware: Apple MacBook Air, M5, 24 GB
GPU family: MTLGPUFamilyApple10 / MTLGPUFamilyMetal4
macOS: Tahoe 26.3.1
Ollama: 0.20.6
Model: gemma4:e4b

**Report**
The device reports MTLGPUFamilyMetal4 (5002) and the crash report   — Metal shader compilation fails with:
static_assert failed due to requirement '__is_same_v<bfloat, half>'
"Input types must match cooperative tensor types"
followed by:
ggml_metal_init: error: failed to initialize the Metal library
ggml_backend_metal_device_init: error: failed to allocate context
GGML_ASSERT(backend) failed
SIGABRT: abort

**Comment by marcolussetti** [comment]
Same behavior reported by @alanhere on Ollama 0.20.7 as well.

Environment:
Hardware: Apple MacBook Pro, M5 Pro, 64 GB
GPU family: MTLGPUFamilyApple10 / MTLGPUFamilyMetal4
macOS: Tahoe 26.3.2
Ollama: 0.20.7
Model: gemma4:31b

**Comment by PureBlissAK** [comment]
## 🤖 Automated Triage & Analysis Report

**Issue**: #15487
**Analyzed**: 2026-04-18T18:21:09.079399

### Analysis
- **Type**: unknown
- **Severity**: medium
- **Components**: unknown

### Implementation Plan
- **Effort**: medium
- **Steps**:

*This issue has been triaged and marked for implementation.*
